export const jokesArr = [
  [
    {
      category: "Programming",
      type: "single",
      joke: "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 37,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup: "Why did the database administrator leave his wife?",
      delivery: "She had one-to-many relationships.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      safe: true,
      id: 265,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "You see, mountains aren't just funny.",
      delivery: "They are hill areas.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      safe: true,
      id: 270,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "What does a woman's pussy and a chainsaw have in common?",
      delivery: "Miss by a few inches and you're in deep shit.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 157,
      safe: false,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "Why do Jewish women prefer circumcised men?",
      delivery: "Cause they won't take anything until it's atleast 10% off.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: true,
      },
      id: 179,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Your mama's so FAT she can't save files bigger than 4GB.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 9,
      safe: false,
      lang: "en",
    },
    {
      category: "Pun",
      type: "single",
      joke: "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 204,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup: "Programming is like sex.",
      delivery:
        "Make one mistake and you end up supporting it for the rest of your life.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 8,
      safe: false,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "Why should you never talk to pi?",
      delivery: "Because it will go on forever.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      safe: true,
      id: 318,
      lang: "en",
    },
    {
      category: "Christmas",
      type: "twopart",
      setup: "How will Christmas dinner be different after Brexit?",
      delivery: "No Brussels!",
      flags: {
        nsfw: false,
        religious: false,
        political: true,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 251,
      safe: false,
      lang: "en",
    },
  ],
  [
    {
      category: "Programming",
      type: "twopart",
      setup: "Programming is like sex.",
      delivery:
        "Make one mistake and you end up supporting it for the rest of your life.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 8,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "If Bill Gates had a dime for every time Windows crashed ... Oh wait, he does.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 22,
      safe: true,
      lang: "en",
    },
    {
      category: "Christmas",
      type: "twopart",
      setup: "What says Oh Oh Oh?",
      delivery: "Santa walking backwards!",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 245,
      safe: true,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "My wife left me because I'm too insecure and paranoid.",
      delivery: "Oh wait, never mind. She was just getting the mail.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 81,
      safe: true,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "Where do sick cruise ships go to get healthy?",
      delivery: "The dock!",
      flags: {
        nsfw: false,
        religious: false,
        political: true,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 212,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup: "Why did the programmer jump on the table?",
      delivery: "Because debug was on his screen.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 214,
      safe: true,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup:
        "I was walking down the street and saw some black guy on a bike and it looked just like mine so I ran home to check.",
      delivery: "Thankfully he was still chained up in my basement.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      id: 124,
      safe: false,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "How does a Jewish person make tea?",
      delivery: "Hebrews it.",
      flags: {
        nsfw: false,
        religious: true,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 131,
      safe: false,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup:
        "Went to the doctors for a prostate exam.\nDuring the exam he said it's not unusual to become aroused or even ejaculate.",
      delivery: "But still, I wish he hadn't.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 83,
      safe: false,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "What do dermatologists and the KKK have in common?",
      delivery: "They both remove blackheads.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      id: 112,
      safe: false,
      lang: "en",
    },
  ],
  [
    {
      category: "Dark",
      type: "twopart",
      setup: "What do dermatologists and the KKK have in common?",
      delivery: "They both remove blackheads.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      id: 112,
      safe: false,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "What did the fish say when it swam into the wall?",
      delivery: "Dam.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 205,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Two C strings walk into a bar.\nThe bartender asks "What can I get ya?"\nThe first string says "I\'ll have a gin and tonic."\nThe second string thinks for a minute, then says "I\'ll take a tequila sunriseJF()#$JF(#)$(@J#()$@#())!*FNIN!OBN134ufh1ui34hf9813f8h8384h981h3984h5F!##@"\nThe first string apologizes, "You\'ll have to excuse my friend, he\'s not null-terminated."',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 28,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "twopart",
      setup: "Why are modern programming languages so materialistic?",
      delivery: "Because they are object-oriented.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 21,
      safe: true,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "What happens when you don't obey the KGB?",
      delivery: "You get Putin jail.",
      flags: {
        nsfw: false,
        religious: false,
        political: true,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 70,
      safe: false,
      lang: "en",
    },
    {
      category: "Dark",
      type: "single",
      joke: 'Nowadays people are so sensitive, you can\'t even say "black paint" anymore.\nInstead, you have to say "Jamal, please paint the fence".',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      id: 133,
      safe: false,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "Why is every gender equality officer female?",
      delivery: "Because it's cheaper.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: true,
        explicit: false,
      },
      id: 61,
      safe: false,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 184,
      safe: false,
      lang: "en",
    },
    {
      category: "Christmas",
      type: "twopart",
      setup: "What does Santa suffer from if he gets stuck in a chimney?",
      delivery: "Claustrophobia!",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 241,
      safe: true,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "I've been in 15 school shootings and I was lucky to survive!",
      delivery: "I just had to be nice with the cops and not resist.",
      flags: {
        nsfw: false,
        religious: false,
        political: true,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 98,
      safe: false,
      lang: "en",
    },
  ],
  [
    {
      category: "Spooky",
      type: "twopart",
      setup: "I'm not saying my son is ugly...",
      delivery:
        "But on Halloween he went to tell the neighbors to turn down their TV and they gave him some candy.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      safe: true,
      id: 313,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "Everyone says that Hitler really loved animals.",
      delivery: "Then why did he kill 6 million of them?",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: true,
      },
      id: 106,
      safe: false,
      lang: "en",
    },
    {
      category: "Dark",
      type: "twopart",
      setup: "What's the difference between a phone and a black person?",
      delivery: "A phone is actually useful.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: true,
        sexist: false,
        explicit: false,
      },
      safe: false,
      id: 309,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 184,
      safe: false,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "I told my wife to shave her pussy.",
      delivery: "I woke up bald.",
      flags: {
        nsfw: true,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: true,
      },
      id: 187,
      safe: false,
      lang: "en",
    },
    {
      category: "Misc",
      type: "twopart",
      setup: "Why was the mushroom always invited to parties?",
      delivery: "Cause he's a fungi.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 223,
      safe: true,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "I walked into a bar once.",
      delivery: "It really hurt my head.",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 215,
      safe: true,
      lang: "en",
    },
    {
      category: "Christmas",
      type: "twopart",
      setup: "What do elves post on Social Media?",
      delivery: "Elf-ies!",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 249,
      safe: true,
      lang: "en",
    },
    {
      category: "Pun",
      type: "twopart",
      setup: "Why do cows wear bells?",
      delivery: "Because their horns don't work!",
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 222,
      safe: true,
      lang: "en",
    },
    {
      category: "Programming",
      type: "single",
      joke: 'Two C strings walk into a bar.\nThe bartender asks "What can I get ya?"\nThe first string says "I\'ll have a gin and tonic."\nThe second string thinks for a minute, then says "I\'ll take a tequila sunriseJF()#$JF(#)$(@J#()$@#())!*FNIN!OBN134ufh1ui34hf9813f8h8384h981h3984h5F!##@"\nThe first string apologizes, "You\'ll have to excuse my friend, he\'s not null-terminated."',
      flags: {
        nsfw: false,
        religious: false,
        political: false,
        racist: false,
        sexist: false,
        explicit: false,
      },
      id: 28,
      safe: true,
      lang: "en",
    },
  ],
];
